// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjs3x-NfS0Vj-TdjDcSMCjp54XleaPQuI',
    appId: '1:281434272077:web:ed99fcc1a47a43094bc704',
    messagingSenderId: '281434272077',
    projectId: 'todo-app-73955',
    authDomain: 'todo-app-73955.firebaseapp.com',
    storageBucket: 'todo-app-73955.appspot.com',
    measurementId: 'G-BSH054X493',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClG8tvc-CwOyHdnwtl22MUmskPHRoq6VM',
    appId: '1:281434272077:android:a5de1776d96b118f4bc704',
    messagingSenderId: '281434272077',
    projectId: 'todo-app-73955',
    storageBucket: 'todo-app-73955.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg78_HCqb2vxO9gZASoPW27zUz7dVAh0U',
    appId: '1:281434272077:ios:a3a173ac576c19d34bc704',
    messagingSenderId: '281434272077',
    projectId: 'todo-app-73955',
    storageBucket: 'todo-app-73955.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg78_HCqb2vxO9gZASoPW27zUz7dVAh0U',
    appId: '1:281434272077:ios:a3a173ac576c19d34bc704',
    messagingSenderId: '281434272077',
    projectId: 'todo-app-73955',
    storageBucket: 'todo-app-73955.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjs3x-NfS0Vj-TdjDcSMCjp54XleaPQuI',
    appId: '1:281434272077:web:050eae5f3e9523c54bc704',
    messagingSenderId: '281434272077',
    projectId: 'todo-app-73955',
    authDomain: 'todo-app-73955.firebaseapp.com',
    storageBucket: 'todo-app-73955.appspot.com',
    measurementId: 'G-KTRLW47R1J',
  );
}
